# Generated by Django 2.0.1 on 2018-03-12 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('university', models.CharField(max_length=128)),
                ('faculty', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('interested_ixp', models.CharField(max_length=128)),
                ('ixp', models.BooleanField(default=False)),
                ('question_why', models.TextField()),
                ('question_expectations', models.TextField()),
                ('question_time', models.CharField(max_length=128)),
                ('question_uniqueness', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_applied', models.BooleanField(default=True)),
                ('date_applied', models.DateTimeField(auto_now=True)),
                ('status_contacted', models.BooleanField(default=False)),
                ('date_contacted', models.DateTimeField(default=None, null=True)),
                ('status_onhold', models.BooleanField(default=False)),
                ('date_onhold', models.DateTimeField(default=None, null=True)),
                ('status_accepted', models.BooleanField(default=False)),
                ('date_accepted', models.DateTimeField(default=None, null=True)),
                ('status_rejected', models.BooleanField(default=False)),
                ('date_rejected', models.DateTimeField(default=None, null=True)),
                ('status_inducted', models.BooleanField(default=False)),
                ('date_inducted', models.DateTimeField(default=None, null=True)),
                ('current_status', models.CharField(blank=True, max_length=128, null=True)),
                ('user_accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_accepted', to=settings.AUTH_USER_MODEL)),
                ('user_contacted', models.ForeignKey(blank=True, null=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_contacted', to=settings.AUTH_USER_MODEL)),
                ('user_inducted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_inducted', to=settings.AUTH_USER_MODEL)),
                ('user_onhold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_onhold', to=settings.AUTH_USER_MODEL)),
                ('user_rejected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rejected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='timeline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Timeline'),
        ),
    ]
