# Generated by Django 2.0.1 on 2018-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='current_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='status_applied',
            field=models.BooleanField(default=True),
        ),
    ]
