# Generated by Django 2.0.1 on 2018-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20180313_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='date_applied',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
