# Generated by Django 2.0.1 on 2018-03-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20180314_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
