# Generated by Django 2.0 on 2017-12-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
