# Generated by Django 2.0 on 2017-12-26 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('external', models.BooleanField(default=False, help_text='Share this form with unregistered users (users who do not have accounts on this system, for example: a recruitment form)? ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_owner', to=settings.AUTH_USER_MODEL)),
                ('share', models.ManyToManyField(blank=True, help_text='Share this with specific people? Leave empty to share with all members', related_name='form_share', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=225)),
                ('required', models.BooleanField(default=False, verbose_name='Required?')),
                ('multiple', models.BooleanField(default=False, help_text='Can the use select more than choice for the answer?', verbose_name='Multiple Answers?')),
                ('choices', models.TextField(blank=True, help_text='Choices, seprated by new lines', null=True)),
                ('type', models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'Text')], default=1)),
                ('order', models.IntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_form', to='form_builder.Form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.BooleanField(default=False)),
                ('visitor_email', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ManyToManyField(related_name='answers_submit', to='form_builder.Answer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form_builder.Form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='form_builder.Question'),
        ),
    ]
