# Generated by Django 2.0 on 2017-12-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invitees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
