# Generated by Django 2.0 on 2017-12-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171226_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='form',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='form',
            name='share',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='submitform',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SubmitForm',
        ),
    ]
