# Generated by Django 2.0 on 2017-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171226_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencepoints',
            options={'verbose_name': 'Experience Points', 'verbose_name_plural': 'Experience Points'},
        ),
        migrations.AlterField(
            model_name='lc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
