# Generated by Django 2.0 on 2017-12-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171226_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lc',
            options={'verbose_name': 'LC', 'verbose_name_plural': 'LCs'},
        ),
    ]
