# Generated by Django 2.0 on 2017-12-27 00:33

import aiesec_hris.core.utility.path_generation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171226_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id_picture',
            field=models.ImageField(upload_to=aiesec_hris.core.utility.path_generation.national_id_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=aiesec_hris.core.utility.path_generation.profile_photo_path),
        ),
    ]
