# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('custom_link', models.TextField(blank=True, help_text='Link to redirect to, if left empty, the absolute url of the content object is used', null=True)),
                ('text', models.TextField()),
                ('action', models.IntegerField(choices=[(1, 'TASK CREATED'), (2, 'TASK ACCEPTED/REJECTED'), (3, 'TASK SUBMITTED'), (10, 'EVENT INVITE'), (20, 'FORM INVITE')])),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
